name: check

on: push

jobs:
  check-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1